# Generated by Django 4.0.6 on 2022-08-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Variation_category',
            new_name='variation_category',
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(default='Blue', max_length=100),
            preserve_default=False,
        ),
    ]
